{"uid":"8657817ba89b7b2d","name":"Display About page","fullName":"Logout functionality.Display About page","historyId":"c647b461798fda5b046a0216b293968c","time":{"start":1736062043346,"stop":1736062056179,"duration":12833},"description":"","descriptionHtml":"","status":"broken","statusMessage":"The following error originated from your application code, not from Cypress.\n                \n                  > Cannot read properties of undefined (reading 'TenantFeatures')\n                \n                This error was thrown by a cross origin page. If you wish to suppress this error you will have to use the cy.origin command to handle the error prior to visiting the page.\n                \n                `cy.origin('https://saucelabs.com', () => {`\n                `  cy.on('uncaught:exception', (e) => {`\n                `    if (e.message.includes('Things went bad')) {`\n                `      // we expected this error, so let's ignore it`\n                `      // and let the test continue`\n                `      return false`\n                `    }`\n                `  })`\n                `})`\n                `cy.visit('https://saucelabs.com/')`\n                \n                When Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n                \n                This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n                \n                https://on.cypress.io/uncaught-exception-from-application\n                \n                https://on.cypress.io/origin","statusTrace":"Error: The following error originated from your application code, not from Cypress.\n                \n                  > Cannot read properties of undefined (reading 'TenantFeatures')\n                \n                This error was thrown by a cross origin page. If you wish to suppress this error you will have to use the cy.origin command to handle the error prior to visiting the page.\n                \n                `cy.origin('https://saucelabs.com', () => {`\n                `  cy.on('uncaught:exception', (e) => {`\n                `    if (e.message.includes('Things went bad')) {`\n                `      // we expected this error, so let's ignore it`\n                `      // and let the test continue`\n                `      return false`\n                `    }`\n                `  })`\n                `})`\n                `cy.visit('https://saucelabs.com/')`\n                \n                When Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n                \n                This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n                \n                https://on.cypress.io/uncaught-exception-from-application\n                \n                https://on.cypress.io/origin\n                    at cypressErr (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:76065:18)\n                    at Object.errByPath (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:76119:10)\n                    at PrimaryOriginCommunicator.<anonymous> (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:169412:72)\n                    at PrimaryOriginCommunicator.emit (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:146238:5)\n                    at PrimaryOriginCommunicator.onMessage (https://www.saucedemo.com/__cypress/runner/cypress_runner.js:168728:12)\n                    at crossOriginOnMessageRef (https://www.saucedemo.com/__/assets/index-h9zRIGOb.js:109348:72)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"suite","value":"Logout functionality"},{"name":"testClass","value":"Logout functionality"},{"name":"testMethod","value":"Display About page"},{"name":"package","value":"Logout functionality"},{"name":"resultFormat","value":"allure1"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"e79c89daafb818a0","status":"broken","statusDetails":"`cy.visit()` failed trying to load:\n                \n                /\n                \n                We failed looking for this file at the path:\n                \n                /home/diniranga/Desktop/Group23_Cypress_Cucumber-dev/Cypress_Cucumber_Test/\n                \n                The internal Cypress web server responded with:\n                \n                  > 404: Not Found","time":{"start":1736050944853,"stop":1736050945212,"duration":359}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"8657817ba89b7b2d.json","parameterValues":[]}